config/routes.rb
Dinnersapp::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "home#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  match 'users/:id' => 'users#show', :as => :user
  match 'past' => 'home#past', :as => :past_dinners
  match 'about' => 'home#about', :as => :about

  resources :restaurants, :only => [:show, :index]
  resources :dinners, :only => [:show] do
    resources :purchases, :only => [:new, :create]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dinners App" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
    <script type="text/javascript">if (window.location.hash == '#_=_')window.location.hash = '';</script>
    <%= javascript_include_tag "jquery" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to image_tag("logo.png", :height => '30'), "/", :class => :brand %>
          <div class="btn-group pull-right">
            <% if user_signed_in? %>
              <%= link_to get_user_picture(current_user), current_user %>
              <%= current_user.name %>
              <%= link_to "Logout", destroy_user_session_path, :method => :delete %>
            <% else %>
              <%= link_to "Sign in", new_user_session_path %>
              <% link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
            <% end %>
          </div>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "dinners", root_path  %></li>
              <li><%= link_to "past dinners", past_dinners_path  %></li>
              <li><%= link_to "near me", restaurants_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span12">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <br />

      <footer>
        <p>&copy; Dinner Company 2012 - <%= link_to "about us", about_path  %></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <%= javascript_include_tag "application" %>
  </body>
</html>